import { format, startOfMonth, endOfMonth, subMonths, eachDayOfInterval } from 'date-fns'
import { Transaction, MonthSummary, CategorySummary, DailyData, CURRENCIES } from '@/types'

export function formatCurrency(amount: number, currencyCode: string = 'USD'): string {
  const currency = CURRENCIES.find(c => c.code === currencyCode)
  const symbol = currency?.symbol || '$'
  return `${symbol}${Math.abs(amount).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`
}

export function getMonthRange(date: Date) {
  return {
    start: startOfMonth(date),
    end: endOfMonth(date),
    label: format(date, 'MMMM yyyy'),
    startLabel: format(startOfMonth(date), 'dd MMM'),
    endLabel: format(endOfMonth(date), 'dd MMM'),
  }
}

export function getDateRangeForFilter(filter: 'month' | 'last_month' | '3months') {
  const now = new Date()
  switch (filter) {
    case 'month':
      return { start: startOfMonth(now), end: endOfMonth(now) }
    case 'last_month':
      const last = subMonths(now, 1)
      return { start: startOfMonth(last), end: endOfMonth(last) }
    case '3months':
      return { start: startOfMonth(subMonths(now, 2)), end: endOfMonth(now) }
  }
}

export function calculateSummary(transactions: Transaction[], daysInMonth: number): MonthSummary {
  const income = transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0)
  const expenses = transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0)
  return {
    income,
    expenses,
    netBalance: income - expenses,
    dailyAverage: daysInMonth > 0 ? Math.round(expenses / daysInMonth) : 0,
    transactionCount: transactions.length,
  }
}

export function calculateCategorySummary(transactions: Transaction[]): CategorySummary[] {
  const expenseTransactions = transactions.filter(t => t.type === 'expense')
  const total = expenseTransactions.reduce((sum, t) => sum + t.amount, 0)
  const categoryMap = new Map<string, { total: number; count: number }>()

  expenseTransactions.forEach(t => {
    const existing = categoryMap.get(t.category) || { total: 0, count: 0 }
    categoryMap.set(t.category, { total: existing.total + t.amount, count: existing.count + 1 })
  })

  return Array.from(categoryMap.entries())
    .map(([category, data]) => ({
      category,
      total: data.total,
      count: data.count,
      percentage: total > 0 ? Math.round((data.total / total) * 100) : 0,
    }))
    .sort((a, b) => b.total - a.total)
}

export function getDailyData(transactions: Transaction[], startDate: Date, endDate: Date): DailyData[] {
  const days = eachDayOfInterval({ start: startDate, end: endDate })
  return days.map(day => {
    const dayStr = format(day, 'yyyy-MM-dd')
    const dayTransactions = transactions.filter(t => t.date === dayStr)
    return {
      date: format(day, 'MMM d'),
      income: dayTransactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0),
      expenses: dayTransactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0),
    }
  })
}

export function exportToCSV(transactions: Transaction[], filename: string = 'transactions') {
  const headers = ['Date', 'Type', 'Category', 'Amount', 'Description']
  const rows = transactions.map(t => [
    t.date,
    t.type,
    t.category,
    t.amount.toString(),
    t.description,
  ])
  const csvContent = [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n')
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = `${filename}_${format(new Date(), 'yyyy-MM-dd')}.csv`
  link.click()
}

export function generateSummaryText(summary: MonthSummary, month: string, currency: string): string {
  return `📊 ExpenseX Report - ${month}
━━━━━━━━━━━━━━━━━━━━━
💰 Net Balance: ${formatCurrency(summary.netBalance, currency)}
📈 Income:      ${formatCurrency(summary.income, currency)}
📉 Expenses:    ${formatCurrency(summary.expenses, currency)}
📅 Daily Avg:   ${formatCurrency(summary.dailyAverage, currency)}
━━━━━━━━━━━━━━━━━━━━━
Generated by ExpenseX`
}

export function getCategoryIcon(category: string): string {
  const icons: Record<string, string> = {
    'Food & Dining': '🍽️', 'Shopping': '🛍️', 'Transportation': '🚗',
    'Housing': '🏠', 'Healthcare': '💊', 'Entertainment': '🎬',
    'Clothing': '👕', 'Education': '📚', 'Utilities': '💡',
    'Salary': '💼', 'Freelance': '💻', 'Investment': '📈',
    'Business': '🏢', 'Gift': '🎁', 'Other': '📦', 'Other Income': '💰',
  }
  return icons[category] || '💳'
}

export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ')
}
